package model

type ClientSettings struct {
	ConfigPath                            string   `json:"configPath,omitempty"`
	User                                  string   `json:"user"`
	ClientID                              string   `json:"clientID"`
	ServerAddr                            string   `json:"serverAddr"`
	ServerPort                            int      `json:"serverPort"`
	NatHoleSTUNServer                     string   `json:"natHoleStunServer"`
	DNSServer                             string   `json:"dnsServer"`
	LoginFailExit                         bool     `json:"loginFailExit"`
	AuthMethod                            string   `json:"authMethod"`
	AuthAdditionalScopes                  []string `json:"authAdditionalScopes"`
	AuthToken                             string   `json:"authToken"`
	AuthTokenSourceType                   string   `json:"authTokenSourceType"`
	AuthTokenSourceFile                   string   `json:"authTokenSourceFile"`
	OIDCClientID                          string   `json:"oidcClientID"`
	OIDCClientSecret                      string   `json:"oidcClientSecret"`
	OIDCAudience                          string   `json:"oidcAudience"`
	OIDCScope                             string   `json:"oidcScope"`
	OIDCTokenEndpointURL                  string   `json:"oidcTokenEndpointURL"`
	OIDCTrustedCaFile                     string   `json:"oidcTrustedCaFile"`
	OIDCInsecureSkipVerify                bool     `json:"oidcInsecureSkipVerify"`
	OIDCProxyURL                          string   `json:"oidcProxyURL"`
	WebServerAddr                         string   `json:"webServerAddr"`
	WebServerPort                         int      `json:"webServerPort"`
	WebServerUser                         string   `json:"webServerUser"`
	WebServerPassword                     string   `json:"webServerPassword"`
	WebServerPprofEnable                  bool     `json:"webServerPprofEnable"`
	StorePath                             string   `json:"storePath"`
	LogTo                                 string   `json:"logTo"`
	LogLevel                              string   `json:"logLevel"`
	LogMaxDays                            int64    `json:"logMaxDays"`
	LogDisablePrintColor                  bool     `json:"logDisablePrintColor"`
	TransportProtocol                     string   `json:"transportProtocol"`
	TransportPoolCount                    int      `json:"transportPoolCount"`
	TransportTCPMux                       bool     `json:"transportTcpMux"`
	TransportTCPMuxKeepaliveInterval      int64    `json:"transportTcpMuxKeepaliveInterval"`
	TransportDialServerTimeout            int64    `json:"transportDialServerTimeout"`
	TransportDialServerKeepalive          int64    `json:"transportDialServerKeepalive"`
	TransportConnectServerLocalIP         string   `json:"transportConnectServerLocalIP"`
	TransportProxyURL                     string   `json:"transportProxyURL"`
	TransportHeartbeatInterval            int64    `json:"transportHeartbeatInterval"`
	TransportHeartbeatTimeout             int64    `json:"transportHeartbeatTimeout"`
	TransportTLSEnable                    bool     `json:"transportTlsEnable"`
	TransportTLSDisableCustomTLSFirstByte bool     `json:"transportTlsDisableCustomTLSFirstByte"`
	TransportTLSCertFile                  string   `json:"transportTlsCertFile"`
	TransportTLSKeyFile                   string   `json:"transportTlsKeyFile"`
	TransportTLSTrustedCaFile             string   `json:"transportTlsTrustedCaFile"`
	TransportTLSServerName                string   `json:"transportTlsServerName"`
	TransportQUICKeepalivePeriod          int      `json:"transportQuicKeepalivePeriod"`
	TransportQUICMaxIdleTimeout           int      `json:"transportQuicMaxIdleTimeout"`
	TransportQUICMaxIncomingStreams       int      `json:"transportQuicMaxIncomingStreams"`
	UDPPacketSize                         int64    `json:"udpPacketSize"`
}
