/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigField: typeof import('./src/components/ConfigField.vue')['default']
    ConfigSection: typeof import('./src/components/ConfigSection.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GuideTypeGrid: typeof import('./src/components/GuideTypeGrid.vue')['default']
    KeyValueEditor: typeof import('./src/components/KeyValueEditor.vue')['default']
    ProxyAuthSection: typeof import('./src/components/proxy-form/ProxyAuthSection.vue')['default']
    ProxyBackendSection: typeof import('./src/components/proxy-form/ProxyBackendSection.vue')['default']
    ProxyBaseSection: typeof import('./src/components/proxy-form/ProxyBaseSection.vue')['default']
    ProxyCard: typeof import('./src/components/ProxyCard.vue')['default']
    ProxyFormLayout: typeof import('./src/components/proxy-form/ProxyFormLayout.vue')['default']
    ProxyHealthSection: typeof import('./src/components/proxy-form/ProxyHealthSection.vue')['default']
    ProxyHttpSection: typeof import('./src/components/proxy-form/ProxyHttpSection.vue')['default']
    ProxyLoadBalanceSection: typeof import('./src/components/proxy-form/ProxyLoadBalanceSection.vue')['default']
    ProxyMetadataSection: typeof import('./src/components/proxy-form/ProxyMetadataSection.vue')['default']
    ProxyNatSection: typeof import('./src/components/proxy-form/ProxyNatSection.vue')['default']
    ProxyRemoteSection: typeof import('./src/components/proxy-form/ProxyRemoteSection.vue')['default']
    ProxyTransportSection: typeof import('./src/components/proxy-form/ProxyTransportSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusPills: typeof import('./src/components/StatusPills.vue')['default']
    StringListEditor: typeof import('./src/components/StringListEditor.vue')['default']
    VisitorBaseSection: typeof import('./src/components/visitor-form/VisitorBaseSection.vue')['default']
    VisitorConnectionSection: typeof import('./src/components/visitor-form/VisitorConnectionSection.vue')['default']
    VisitorFormLayout: typeof import('./src/components/visitor-form/VisitorFormLayout.vue')['default']
    VisitorTransportSection: typeof import('./src/components/visitor-form/VisitorTransportSection.vue')['default']
    VisitorXtcpSection: typeof import('./src/components/visitor-form/VisitorXtcpSection.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
