export interface ClientSettings {
  configPath: string
  user: string
  clientID: string
  serverAddr: string
  serverPort: number
  natHoleStunServer: string
  dnsServer: string
  loginFailExit: boolean
  authMethod: string
  authAdditionalScopes: string[]
  authToken: string
  authTokenSourceType: string
  authTokenSourceFile: string
  oidcClientID: string
  oidcClientSecret: string
  oidcAudience: string
  oidcScope: string
  oidcTokenEndpointURL: string
  oidcTrustedCaFile: string
  oidcInsecureSkipVerify: boolean
  oidcProxyURL: string
  webServerAddr: string
  webServerPort: number
  webServerUser: string
  webServerPassword: string
  webServerPprofEnable: boolean
  storePath: string
  logTo: string
  logLevel: string
  logMaxDays: number
  logDisablePrintColor: boolean
  transportProtocol: string
  transportPoolCount: number
  transportTcpMux: boolean
  transportTcpMuxKeepaliveInterval: number
  transportDialServerTimeout: number
  transportDialServerKeepalive: number
  transportConnectServerLocalIP: string
  transportProxyURL: string
  transportHeartbeatInterval: number
  transportHeartbeatTimeout: number
  transportTlsEnable: boolean
  transportTlsDisableCustomTLSFirstByte: boolean
  transportTlsCertFile: string
  transportTlsKeyFile: string
  transportTlsTrustedCaFile: string
  transportTlsServerName: string
  transportQuicKeepalivePeriod: number
  transportQuicMaxIdleTimeout: number
  transportQuicMaxIncomingStreams: number
  udpPacketSize: number
}
