name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Build classic web assets (frps)
        run: npm install && npm run build
        working-directory: web/frps
      - name: Build classic web assets (frpc)
        run: npm install && npm run build
        working-directory: web/frpc
      - name: Build custom webui assets (frps)
        run: npm install && npm run build
        working-directory: webui/frps
      - name: Build custom webui assets (frpc)
        run: npm install && npm run build
        working-directory: webui/frpc
      - name: Make All
        run: |
          ./package.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean --release-notes=./Release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
